// Package v20260729 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v20260729

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateContributingDevsRequestBodyDataType.
const (
	ContributingDevs CreateContributingDevsRequestBodyDataType = "contributing_devs"
)

// ContributingDevsIngestAttributes defines model for ContributingDevsIngestAttributes.
type ContributingDevsIngestAttributes struct {
	Contributors         []Contributor `json:"contributors"`
	ContributorsEntityId string        `json:"contributors_entity_id"`
}

// Contributor defines model for Contributor.
type Contributor struct {
	CommitDate time.Time `json:"commit_date"`
	Email      string    `json:"email"`
}

// CreateContributingDevsRequestBody defines model for CreateContributingDevsRequestBody.
type CreateContributingDevsRequestBody struct {
	Data struct {
		Attributes ContributingDevsIngestAttributes          `json:"attributes"`
		Type       CreateContributingDevsRequestBodyDataType `json:"type"`
	} `json:"data"`
}

// CreateContributingDevsRequestBodyDataType defines model for CreateContributingDevsRequestBody.Data.Type.
type CreateContributingDevsRequestBodyDataType string

// CreateContributingDevsResponseBody defines model for CreateContributingDevsResponseBody.
type CreateContributingDevsResponseBody struct {
	Data struct {
		Id   string `json:"id"`
		Type string `json:"type"`
	} `json:"data"`
}

// CreateContributingDevsParams defines parameters for CreateContributingDevs.
type CreateContributingDevsParams struct {
	Version string `form:"version" json:"version"`
}

// CreateContributingDevsApplicationVndAPIPlusJSONRequestBody defines body for CreateContributingDevs for application/vnd.api+json ContentType.
type CreateContributingDevsApplicationVndAPIPlusJSONRequestBody = CreateContributingDevsRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateContributingDevsWithBody request with any body
	CreateContributingDevsWithBody(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateContributingDevsWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, body CreateContributingDevsApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateContributingDevsWithBody(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateContributingDevsRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateContributingDevsWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, body CreateContributingDevsApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateContributingDevsRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateContributingDevsRequestWithApplicationVndAPIPlusJSONBody calls the generic CreateContributingDevs builder with application/vnd.api+json body
func NewCreateContributingDevsRequestWithApplicationVndAPIPlusJSONBody(server string, orgId openapi_types.UUID, params *CreateContributingDevsParams, body CreateContributingDevsApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateContributingDevsRequestWithBody(server, orgId, params, "application/vnd.api+json", bodyReader)
}

// NewCreateContributingDevsRequestWithBody generates requests for CreateContributingDevs with any type of body
func NewCreateContributingDevsRequestWithBody(server string, orgId openapi_types.UUID, params *CreateContributingDevsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hidden/orgs/%s/contributing_devs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateContributingDevsWithBodyWithResponse request with any body
	CreateContributingDevsWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateContributingDevsResponse, error)

	CreateContributingDevsWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, body CreateContributingDevsApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateContributingDevsResponse, error)
}

type CreateContributingDevsResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON201 *CreateContributingDevsResponseBody
}

// Status returns HTTPResponse.Status
func (r CreateContributingDevsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateContributingDevsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateContributingDevsWithBodyWithResponse request with arbitrary body returning *CreateContributingDevsResponse
func (c *ClientWithResponses) CreateContributingDevsWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateContributingDevsResponse, error) {
	rsp, err := c.CreateContributingDevsWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateContributingDevsResponse(rsp)
}

func (c *ClientWithResponses) CreateContributingDevsWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateContributingDevsParams, body CreateContributingDevsApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateContributingDevsResponse, error) {
	rsp, err := c.CreateContributingDevsWithApplicationVndAPIPlusJSONBody(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateContributingDevsResponse(rsp)
}

// ParseCreateContributingDevsResponse parses an HTTP response from a CreateContributingDevsWithResponse call
func ParseCreateContributingDevsResponse(rsp *http.Response) (*CreateContributingDevsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateContributingDevsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateContributingDevsResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON201 = &dest

	}

	return response, nil
}
