// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: extension.proto

package extensionpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadEncoding int32

const (
	PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED PayloadEncoding = 0 // nil payload
	PayloadEncoding_PAYLOAD_ENCODING_BYTES       PayloadEncoding = 1 // []byte, sent verbatim
	PayloadEncoding_PAYLOAD_ENCODING_STRING      PayloadEncoding = 2 // string
	PayloadEncoding_PAYLOAD_ENCODING_JSON        PayloadEncoding = 3 // any other value, JSON-encoded
)

// Enum value maps for PayloadEncoding.
var (
	PayloadEncoding_name = map[int32]string{
		0: "PAYLOAD_ENCODING_UNSPECIFIED",
		1: "PAYLOAD_ENCODING_BYTES",
		2: "PAYLOAD_ENCODING_STRING",
		3: "PAYLOAD_ENCODING_JSON",
	}
	PayloadEncoding_value = map[string]int32{
		"PAYLOAD_ENCODING_UNSPECIFIED": 0,
		"PAYLOAD_ENCODING_BYTES":       1,
		"PAYLOAD_ENCODING_STRING":      2,
		"PAYLOAD_ENCODING_JSON":        3,
	}
)

func (x PayloadEncoding) Enum() *PayloadEncoding {
	p := new(PayloadEncoding)
	*p = x
	return p
}

func (x PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_proto_enumTypes[0].Descriptor()
}

func (PayloadEncoding) Type() protoreflect.EnumType {
	return &file_extension_proto_enumTypes[0]
}

func (x PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEncoding.Descriptor instead.
func (PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowSpec        `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverResponse) GetWorkflows() []*WorkflowSpec {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// WorkflowSpec mirrors what an in-process extension registers via
// engine.Register: an identifier, visibility, and its configuration flags.
type WorkflowSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"` // workflow identifier URL, e.g. "flw://hello"
	Visible       bool                   `protobuf:"varint,2,opt,name=visible,proto3" json:"visible,omitempty"`
	Flags         []*FlagSpec            `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSpec) Reset() {
	*x = WorkflowSpec{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSpec) ProtoMessage() {}

func (x *WorkflowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSpec.ProtoReflect.Descriptor instead.
func (*WorkflowSpec) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowSpec) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WorkflowSpec) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *WorkflowSpec) GetFlags() []*FlagSpec {
	if x != nil {
		return x.Flags
	}
	return nil
}

// FlagSpec describes one configuration option the workflow understands. The
// host uses these both to build CLI flags and to decide which configuration
// values are exported to the extension at Execute time.
type FlagSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "bool" | "string" | "int"
	DefaultValue  string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Usage         string                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagSpec) Reset() {
	*x = FlagSpec{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagSpec) ProtoMessage() {}

func (x *FlagSpec) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagSpec.ProtoReflect.Descriptor instead.
func (*FlagSpec) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *FlagSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlagSpec) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FlagSpec) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type ExecuteRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// config is the snapshot of configuration values the host exports to the
	// extension. Only keys the extension declared via FlagSpec are included.
	Config map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Input  []*DataMsg        `protobuf:"bytes,3,rep,name=input,proto3" json:"input,omitempty"`
	// network_proxy_url and network_proxy_token connect the extension to the
	// host's authenticated network access (the "option C" loopback auth proxy).
	// When set, the extension makes plain HTTP requests to network_proxy_url and
	// the host injects the user's credentials before forwarding upstream. Empty
	// when no network access is provided to this invocation.
	NetworkProxyUrl   string `protobuf:"bytes,4,opt,name=network_proxy_url,json=networkProxyUrl,proto3" json:"network_proxy_url,omitempty"`
	NetworkProxyToken string `protobuf:"bytes,5,opt,name=network_proxy_token,json=networkProxyToken,proto3" json:"network_proxy_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ExecuteRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteRequest) GetInput() []*DataMsg {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetNetworkProxyUrl() string {
	if x != nil {
		return x.NetworkProxyUrl
	}
	return ""
}

func (x *ExecuteRequest) GetNetworkProxyToken() string {
	if x != nil {
		return x.NetworkProxyToken
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []*DataMsg             `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetOutput() []*DataMsg {
	if x != nil {
		return x.Output
	}
	return nil
}

// DataMsg is the wire form of workflow.Data. Payloads are transported as bytes
// with an explicit encoding so the receiver can reconstruct the original Go
// value.
type DataMsg struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Identifier      string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadEncoding PayloadEncoding        `protobuf:"varint,4,opt,name=payload_encoding,json=payloadEncoding,proto3,enum=snyk.extension.v1.PayloadEncoding" json:"payload_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataMsg) Reset() {
	*x = DataMsg{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMsg) ProtoMessage() {}

func (x *DataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMsg.ProtoReflect.Descriptor instead.
func (*DataMsg) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *DataMsg) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *DataMsg) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataMsg) GetPayloadEncoding() PayloadEncoding {
	if x != nil {
		return x.PayloadEncoding
	}
	return PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\x11snyk.extension.v1\"\x11\n" +
	"\x0fDiscoverRequest\"Q\n" +
	"\x10DiscoverResponse\x12=\n" +
	"\tworkflows\x18\x01 \x03(\v2\x1f.snyk.extension.v1.WorkflowSpecR\tworkflows\"{\n" +
	"\fWorkflowSpec\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x18\n" +
	"\avisible\x18\x02 \x01(\bR\avisible\x121\n" +
	"\x05flags\x18\x03 \x03(\v2\x1b.snyk.extension.v1.FlagSpecR\x05flags\"m\n" +
	"\bFlagSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\tR\x05usage\"\xc0\x02\n" +
	"\x0eExecuteRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12E\n" +
	"\x06config\x18\x02 \x03(\v2-.snyk.extension.v1.ExecuteRequest.ConfigEntryR\x06config\x120\n" +
	"\x05input\x18\x03 \x03(\v2\x1a.snyk.extension.v1.DataMsgR\x05input\x12*\n" +
	"\x11network_proxy_url\x18\x04 \x01(\tR\x0fnetworkProxyUrl\x12.\n" +
	"\x13network_proxy_token\x18\x05 \x01(\tR\x11networkProxyToken\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x0fExecuteResponse\x122\n" +
	"\x06output\x18\x01 \x03(\v2\x1a.snyk.extension.v1.DataMsgR\x06output\"\x95\x02\n" +
	"\aDataMsg\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12D\n" +
	"\bmetadata\x18\x02 \x03(\v2(.snyk.extension.v1.DataMsg.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12M\n" +
	"\x10payload_encoding\x18\x04 \x01(\x0e2\".snyk.extension.v1.PayloadEncodingR\x0fpayloadEncoding\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x87\x01\n" +
	"\x0fPayloadEncoding\x12 \n" +
	"\x1cPAYLOAD_ENCODING_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYLOAD_ENCODING_BYTES\x10\x01\x12\x1b\n" +
	"\x17PAYLOAD_ENCODING_STRING\x10\x02\x12\x19\n" +
	"\x15PAYLOAD_ENCODING_JSON\x10\x032\xb2\x01\n" +
	"\tExtension\x12S\n" +
	"\bDiscover\x12\".snyk.extension.v1.DiscoverRequest\x1a#.snyk.extension.v1.DiscoverResponse\x12P\n" +
	"\aExecute\x12!.snyk.extension.v1.ExecuteRequest\x1a\".snyk.extension.v1.ExecuteResponseBJZHgithub.com/snyk/go-application-framework/pkg/extension/proto;extensionpbb\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_extension_proto_goTypes = []any{
	(PayloadEncoding)(0),     // 0: snyk.extension.v1.PayloadEncoding
	(*DiscoverRequest)(nil),  // 1: snyk.extension.v1.DiscoverRequest
	(*DiscoverResponse)(nil), // 2: snyk.extension.v1.DiscoverResponse
	(*WorkflowSpec)(nil),     // 3: snyk.extension.v1.WorkflowSpec
	(*FlagSpec)(nil),         // 4: snyk.extension.v1.FlagSpec
	(*ExecuteRequest)(nil),   // 5: snyk.extension.v1.ExecuteRequest
	(*ExecuteResponse)(nil),  // 6: snyk.extension.v1.ExecuteResponse
	(*DataMsg)(nil),          // 7: snyk.extension.v1.DataMsg
	nil,                      // 8: snyk.extension.v1.ExecuteRequest.ConfigEntry
	nil,                      // 9: snyk.extension.v1.DataMsg.MetadataEntry
}
var file_extension_proto_depIdxs = []int32{
	3, // 0: snyk.extension.v1.DiscoverResponse.workflows:type_name -> snyk.extension.v1.WorkflowSpec
	4, // 1: snyk.extension.v1.WorkflowSpec.flags:type_name -> snyk.extension.v1.FlagSpec
	8, // 2: snyk.extension.v1.ExecuteRequest.config:type_name -> snyk.extension.v1.ExecuteRequest.ConfigEntry
	7, // 3: snyk.extension.v1.ExecuteRequest.input:type_name -> snyk.extension.v1.DataMsg
	7, // 4: snyk.extension.v1.ExecuteResponse.output:type_name -> snyk.extension.v1.DataMsg
	9, // 5: snyk.extension.v1.DataMsg.metadata:type_name -> snyk.extension.v1.DataMsg.MetadataEntry
	0, // 6: snyk.extension.v1.DataMsg.payload_encoding:type_name -> snyk.extension.v1.PayloadEncoding
	1, // 7: snyk.extension.v1.Extension.Discover:input_type -> snyk.extension.v1.DiscoverRequest
	5, // 8: snyk.extension.v1.Extension.Execute:input_type -> snyk.extension.v1.ExecuteRequest
	2, // 9: snyk.extension.v1.Extension.Discover:output_type -> snyk.extension.v1.DiscoverResponse
	6, // 10: snyk.extension.v1.Extension.Execute:output_type -> snyk.extension.v1.ExecuteResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		EnumInfos:         file_extension_proto_enumTypes,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
