// Code generated by MockGen. DO NOT EDIT.
// Source: testapi.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	testapi "github.com/snyk/go-application-framework/pkg/apiclients/testapi"
)

// MockTestResult is a mock of TestResult interface.
type MockTestResult struct {
	ctrl     *gomock.Controller
	recorder *MockTestResultMockRecorder
}

// MockTestResultMockRecorder is the mock recorder for MockTestResult.
type MockTestResultMockRecorder struct {
	mock *MockTestResult
}

// NewMockTestResult creates a new mock instance.
func NewMockTestResult(ctrl *gomock.Controller) *MockTestResult {
	mock := &MockTestResult{ctrl: ctrl}
	mock.recorder = &MockTestResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestResult) EXPECT() *MockTestResultMockRecorder {
	return m.recorder
}

// Findings mocks base method.
func (m *MockTestResult) Findings(ctx context.Context) ([]testapi.FindingData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Findings", ctx)
	ret0, _ := ret[0].([]testapi.FindingData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Findings indicates an expected call of Findings.
func (mr *MockTestResultMockRecorder) Findings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Findings", reflect.TypeOf((*MockTestResult)(nil).Findings), ctx)
}

// GetBreachedPolicies mocks base method.
func (m *MockTestResult) GetBreachedPolicies() *testapi.PolicyRefSet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreachedPolicies")
	ret0, _ := ret[0].(*testapi.PolicyRefSet)
	return ret0
}

// GetBreachedPolicies indicates an expected call of GetBreachedPolicies.
func (mr *MockTestResultMockRecorder) GetBreachedPolicies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreachedPolicies", reflect.TypeOf((*MockTestResult)(nil).GetBreachedPolicies))
}

// GetCreatedAt mocks base method.
func (m *MockTestResult) GetCreatedAt() *time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedAt")
	ret0, _ := ret[0].(*time.Time)
	return ret0
}

// GetCreatedAt indicates an expected call of GetCreatedAt.
func (mr *MockTestResultMockRecorder) GetCreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedAt", reflect.TypeOf((*MockTestResult)(nil).GetCreatedAt))
}

// GetEffectiveSummary mocks base method.
func (m *MockTestResult) GetEffectiveSummary() *testapi.FindingSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffectiveSummary")
	ret0, _ := ret[0].(*testapi.FindingSummary)
	return ret0
}

// GetEffectiveSummary indicates an expected call of GetEffectiveSummary.
func (mr *MockTestResultMockRecorder) GetEffectiveSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffectiveSummary", reflect.TypeOf((*MockTestResult)(nil).GetEffectiveSummary))
}

// GetErrors mocks base method.
func (m *MockTestResult) GetErrors() *[]testapi.IoSnykApiCommonError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrors")
	ret0, _ := ret[0].(*[]testapi.IoSnykApiCommonError)
	return ret0
}

// GetErrors indicates an expected call of GetErrors.
func (mr *MockTestResultMockRecorder) GetErrors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrors", reflect.TypeOf((*MockTestResult)(nil).GetErrors))
}

// GetExecutionState mocks base method.
func (m *MockTestResult) GetExecutionState() testapi.TestExecutionStates {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionState")
	ret0, _ := ret[0].(testapi.TestExecutionStates)
	return ret0
}

// GetExecutionState indicates an expected call of GetExecutionState.
func (mr *MockTestResultMockRecorder) GetExecutionState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionState", reflect.TypeOf((*MockTestResult)(nil).GetExecutionState))
}

// GetMetadata mocks base method.
func (m *MockTestResult) GetMetadata() map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockTestResultMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockTestResult)(nil).GetMetadata))
}

// GetOutcomeReason mocks base method.
func (m *MockTestResult) GetOutcomeReason() *testapi.TestOutcomeReason {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutcomeReason")
	ret0, _ := ret[0].(*testapi.TestOutcomeReason)
	return ret0
}

// GetOutcomeReason indicates an expected call of GetOutcomeReason.
func (mr *MockTestResultMockRecorder) GetOutcomeReason() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutcomeReason", reflect.TypeOf((*MockTestResult)(nil).GetOutcomeReason))
}

// GetPassFail mocks base method.
func (m *MockTestResult) GetPassFail() *testapi.PassFail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassFail")
	ret0, _ := ret[0].(*testapi.PassFail)
	return ret0
}

// GetPassFail indicates an expected call of GetPassFail.
func (mr *MockTestResultMockRecorder) GetPassFail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassFail", reflect.TypeOf((*MockTestResult)(nil).GetPassFail))
}

// GetRawSummary mocks base method.
func (m *MockTestResult) GetRawSummary() *testapi.FindingSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawSummary")
	ret0, _ := ret[0].(*testapi.FindingSummary)
	return ret0
}

// GetRawSummary indicates an expected call of GetRawSummary.
func (mr *MockTestResultMockRecorder) GetRawSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawSummary", reflect.TypeOf((*MockTestResult)(nil).GetRawSummary))
}

// GetSubjectLocators mocks base method.
func (m *MockTestResult) GetSubjectLocators() *[]testapi.TestSubjectLocator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubjectLocators")
	ret0, _ := ret[0].(*[]testapi.TestSubjectLocator)
	return ret0
}

// GetSubjectLocators indicates an expected call of GetSubjectLocators.
func (mr *MockTestResultMockRecorder) GetSubjectLocators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubjectLocators", reflect.TypeOf((*MockTestResult)(nil).GetSubjectLocators))
}

// GetTestConfiguration mocks base method.
func (m *MockTestResult) GetTestConfiguration() *testapi.TestConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestConfiguration")
	ret0, _ := ret[0].(*testapi.TestConfiguration)
	return ret0
}

// GetTestConfiguration indicates an expected call of GetTestConfiguration.
func (mr *MockTestResultMockRecorder) GetTestConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestConfiguration", reflect.TypeOf((*MockTestResult)(nil).GetTestConfiguration))
}

// GetTestID mocks base method.
func (m *MockTestResult) GetTestID() *uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestID")
	ret0, _ := ret[0].(*uuid.UUID)
	return ret0
}

// GetTestID indicates an expected call of GetTestID.
func (mr *MockTestResultMockRecorder) GetTestID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestID", reflect.TypeOf((*MockTestResult)(nil).GetTestID))
}

// GetTestSubject mocks base method.
func (m *MockTestResult) GetTestSubject() testapi.TestSubject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestSubject")
	ret0, _ := ret[0].(testapi.TestSubject)
	return ret0
}

// GetTestSubject indicates an expected call of GetTestSubject.
func (mr *MockTestResultMockRecorder) GetTestSubject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestSubject", reflect.TypeOf((*MockTestResult)(nil).GetTestSubject))
}

// GetWarnings mocks base method.
func (m *MockTestResult) GetWarnings() *[]testapi.IoSnykApiCommonError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarnings")
	ret0, _ := ret[0].(*[]testapi.IoSnykApiCommonError)
	return ret0
}

// GetWarnings indicates an expected call of GetWarnings.
func (mr *MockTestResultMockRecorder) GetWarnings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarnings", reflect.TypeOf((*MockTestResult)(nil).GetWarnings))
}

// SetMetadata mocks base method.
func (m *MockTestResult) SetMetadata(key string, value interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetadata", key, value)
}

// SetMetadata indicates an expected call of SetMetadata.
func (mr *MockTestResultMockRecorder) SetMetadata(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*MockTestResult)(nil).SetMetadata), key, value)
}

// MockTestHandle is a mock of TestHandle interface.
type MockTestHandle struct {
	ctrl     *gomock.Controller
	recorder *MockTestHandleMockRecorder
}

// MockTestHandleMockRecorder is the mock recorder for MockTestHandle.
type MockTestHandleMockRecorder struct {
	mock *MockTestHandle
}

// NewMockTestHandle creates a new mock instance.
func NewMockTestHandle(ctrl *gomock.Controller) *MockTestHandle {
	mock := &MockTestHandle{ctrl: ctrl}
	mock.recorder = &MockTestHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestHandle) EXPECT() *MockTestHandleMockRecorder {
	return m.recorder
}

// Done mocks base method.
func (m *MockTestHandle) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockTestHandleMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockTestHandle)(nil).Done))
}

// Result mocks base method.
func (m *MockTestHandle) Result() testapi.TestResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Result")
	ret0, _ := ret[0].(testapi.TestResult)
	return ret0
}

// Result indicates an expected call of Result.
func (mr *MockTestHandleMockRecorder) Result() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Result", reflect.TypeOf((*MockTestHandle)(nil).Result))
}

// Wait mocks base method.
func (m *MockTestHandle) Wait(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockTestHandleMockRecorder) Wait(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockTestHandle)(nil).Wait), ctx)
}

// MockTestClient is a mock of TestClient interface.
type MockTestClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestClientMockRecorder
}

// MockTestClientMockRecorder is the mock recorder for MockTestClient.
type MockTestClientMockRecorder struct {
	mock *MockTestClient
}

// NewMockTestClient creates a new mock instance.
func NewMockTestClient(ctrl *gomock.Controller) *MockTestClient {
	mock := &MockTestClient{ctrl: ctrl}
	mock.recorder = &MockTestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestClient) EXPECT() *MockTestClientMockRecorder {
	return m.recorder
}

// StartTest mocks base method.
func (m *MockTestClient) StartTest(ctx context.Context, params testapi.StartTestParams) (testapi.TestHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTest", ctx, params)
	ret0, _ := ret[0].(testapi.TestHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTest indicates an expected call of StartTest.
func (mr *MockTestClientMockRecorder) StartTest(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTest", reflect.TypeOf((*MockTestClient)(nil).StartTest), ctx, params)
}
