// Code generated by MockGen. DO NOT EDIT.
// Source: progressbar.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProgressBar is a mock of ProgressBar interface.
type MockProgressBar struct {
	ctrl     *gomock.Controller
	recorder *MockProgressBarMockRecorder
}

// MockProgressBarMockRecorder is the mock recorder for MockProgressBar.
type MockProgressBarMockRecorder struct {
	mock *MockProgressBar
}

// NewMockProgressBar creates a new mock instance.
func NewMockProgressBar(ctrl *gomock.Controller) *MockProgressBar {
	mock := &MockProgressBar{ctrl: ctrl}
	mock.recorder = &MockProgressBarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressBar) EXPECT() *MockProgressBarMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockProgressBar) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockProgressBarMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockProgressBar)(nil).Clear))
}

// UpdateProgress mocks base method.
func (m *MockProgressBar) UpdateProgress(progress float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockProgressBarMockRecorder) UpdateProgress(progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockProgressBar)(nil).UpdateProgress), progress)
}

// UpdateProgressWithMessage mocks base method.
func (m *MockProgressBar) UpdateProgressWithMessage(progress float64, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgressWithMessage", progress, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgressWithMessage indicates an expected call of UpdateProgressWithMessage.
func (mr *MockProgressBarMockRecorder) UpdateProgressWithMessage(progress, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgressWithMessage", reflect.TypeOf((*MockProgressBar)(nil).UpdateProgressWithMessage), progress, message)
}

// MockProgressBarInfinite is a mock of ProgressBarInfinite interface.
type MockProgressBarInfinite struct {
	ctrl     *gomock.Controller
	recorder *MockProgressBarInfiniteMockRecorder
}

// MockProgressBarInfiniteMockRecorder is the mock recorder for MockProgressBarInfinite.
type MockProgressBarInfiniteMockRecorder struct {
	mock *MockProgressBarInfinite
}

// NewMockProgressBarInfinite creates a new mock instance.
func NewMockProgressBarInfinite(ctrl *gomock.Controller) *MockProgressBarInfinite {
	mock := &MockProgressBarInfinite{ctrl: ctrl}
	mock.recorder = &MockProgressBarInfiniteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressBarInfinite) EXPECT() *MockProgressBarInfiniteMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockProgressBarInfinite) Clear() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockProgressBarInfiniteMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockProgressBarInfinite)(nil).Clear))
}

// SetMessage mocks base method.
func (m *MockProgressBarInfinite) SetMessage(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessage indicates an expected call of SetMessage.
func (mr *MockProgressBarInfiniteMockRecorder) SetMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockProgressBarInfinite)(nil).SetMessage), message)
}
