openapi: 3.0.0
info:
  title: Legacy Test Dependency Graph API
  version: v1
  description: |-
    The Snyk Test API to run, re-run, list, fetch, or cancel any supported test
    at Snyk.
tags:
  - name: Legacy Test
paths:
  /test-dep-graph:
    post:
      operationId: testDepGraph
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      tags:
        - Legacy Test
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
components:
  schemas:
    AffectedPackage:
      type: object
      required:
        - pkg
        - issues
      properties:
        pkg:
          $ref: '#/components/schemas/Package'
        issues:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Issue'
      additionalProperties: {}
    CvssDetails:
      type: object
      properties:
        assigner:
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        cvssV3Vector:
          type: string
        cvssV3BaseScore:
          type: number
          format: double
        modificationTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
      additionalProperties: {}
    CvssSource:
      type: object
      required:
        - modificationTime
      properties:
        type:
          type: string
        vector:
          type: string
        assigner:
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        baseScore:
          type: number
          format: double
        cvssVersion:
          type: string
        modificationTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
      additionalProperties: {}
    EpssDetails:
      type: object
      properties:
        percentile:
          type: string
        probability:
          type: string
        modelVersion:
          type: string
      additionalProperties: {}
    ExploitDetails:
      type: object
      properties:
        sources:
          type: array
          items: {}
        maturityLevels:
          type: array
          items:
            $ref: '#/components/schemas/MaturityLevel'
      additionalProperties: {}
    FixInfo:
      type: object
      required:
        - isPatchable
        - upgradePaths
      properties:
        isPatchable:
          type: boolean
        upgradePaths:
          type: array
          items:
            $ref: '#/components/schemas/UpgradePath'
        isRuntime:
          type: boolean
        isPinnable:
          type: boolean
      additionalProperties: {}
    IgnoreSettings:
      type: object
      required:
        - adminOnly
        - reasonRequired
        - disregardFilesystemIgnores
      properties:
        adminOnly:
          type: boolean
        reasonRequired:
          type: boolean
        disregardFilesystemIgnores:
          type: boolean
      additionalProperties: {}
    Issue:
      type: object
      required:
        - issueId
        - fixInfo
      properties:
        issueId:
          type: string
        fixInfo:
          $ref: '#/components/schemas/FixInfo'
      additionalProperties: {}
    IssueData:
      type: object
      required:
        - id
        - title
        - semver
        - fixedIn
        - language
        - severity
        - cvssScore
        - moduleName
        - description
        - packageName
        - packageManager
        - severityWithCritical
      properties:
        id:
          type: string
        title:
          type: string
        CVSSv3:
          type: string
        credit:
          type: array
          items:
            type: string
        semver:
          type: object
          properties:
            vulnerable:
              type: array
              items:
                type: string
              description: Ranges of vulnerable versions
          required:
            - vulnerable
        exploit:
          type: string
        fixedIn:
          type: array
          items:
            type: string
          description: |-
            List of versions in which the vulnerability is fixed.

            TODO: can this be a range too?
        patches:
          type: array
          items:
            type: string
        insights:
          type: object
          additionalProperties: {}
        language:
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        cvssScore:
          type: number
          format: double
        functions:
          type: array
          items: {}
        malicious:
          type: boolean
        isDisputed:
          type: boolean
        moduleName:
          type: string
        references:
          type: array
          items:
            $ref: '#/components/schemas/IssueReferences'
        cvssDetails:
          type: array
          items:
            $ref: '#/components/schemas/CvssDetails'
        cvssSources:
          type: array
          items:
            $ref: '#/components/schemas/CvssSource'
        description:
          type: string
        epssDetails:
          type: object
          allOf:
            - $ref: '#/components/schemas/EpssDetails'
          nullable: true
        identifiers:
          $ref: '#/components/schemas/IssueIdentifiers'
        packageName:
          type: string
        proprietary:
          type: boolean
          enum:
            - false
        creationTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
        functions_new:
          type: array
          items: {}
        alternativeIds:
          type: array
          items: {}
        disclosureTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
        exploitDetails:
          $ref: '#/components/schemas/ExploitDetails'
        packageManager:
          type: string
        publicationTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
        severityBasedOn:
          type: string
        modificationTime:
          $ref: '#/components/schemas/rfc3339Microseconds'
        socialTrendAlert:
          type: boolean
        severityWithCritical:
          $ref: '#/components/schemas/Severity'
        name:
          type: string
        version:
          type: string
        from:
          type: array
          items:
            type: string
      additionalProperties: {}
    IssueIdentifiers:
      type: object
      properties:
        CVE:
          type: array
          items:
            type: string
        CWE:
          type: array
          items:
            type: string
      additionalProperties: {}
    IssueReferences:
      type: object
      required:
        - url
      properties:
        url:
          type: string
        title:
          type: string
      additionalProperties: {}
    LicenseSeverity:
      type: object
      required:
        - licenseType
        - severity
        - instructions
      properties:
        licenseType:
          type: string
        severity:
          $ref: '#/components/schemas/Severity'
        instructions:
          type: string
      additionalProperties: {}
    LicensesPolicy:
      type: object
      required:
        - severities
        - orgLicenseRules
      properties:
        severities:
          type: object
          additionalProperties: {}
        orgLicenseRules:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/LicenseSeverity'
      additionalProperties: {}
    MaturityLevel:
      type: object
      properties:
        type:
          type: string
        level:
          type: string
        format:
          type: string
      additionalProperties: {}
    Meta:
      type: object
      required:
        - isPrivate
        - isLicensesEnabled
        - projectId
        - policy
        - ignoreSettings
        - org
        - licensesPolicy
      properties:
        isPrivate:
          type: boolean
        isLicensesEnabled:
          type: boolean
        projectId:
          type: string
        policy:
          type: string
        ignoreSettings:
          $ref: '#/components/schemas/IgnoreSettings'
        org:
          type: string
        licensesPolicy:
          $ref: '#/components/schemas/LicensesPolicy'
      additionalProperties: {}
    Package:
      type: object
      required:
        - name
        - version
      properties:
        name:
          type: string
        version:
          type: string
      additionalProperties: {}
    PackageUpgrade:
      type: object
      required:
        - newVersion
      properties:
        newVersion:
          type: string
      additionalProperties: {}
      allOf:
        - $ref: '#/components/schemas/Package'
    PatchObject:
      type: object
      required:
        - patched
      properties:
        patched:
          type: string
      additionalProperties: {}
    PatchRemediation:
      type: object
      required:
        - paths
      properties:
        paths:
          type: array
          items:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/PatchObject'
      additionalProperties: {}
    Remediation:
      type: object
      required:
        - unresolved
        - upgrade
        - patch
        - ignore
        - pin
      properties:
        unresolved:
          type: array
          items:
            $ref: '#/components/schemas/IssueData'
        upgrade:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UpgradePackage'
        patch:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PatchRemediation'
        ignore:
          type: object
          additionalProperties: {}
        pin:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/UpgradePackage'
      additionalProperties: {}
    ResponseBody:
      type: object
      required:
        - result
        - meta
      properties:
        result:
          $ref: '#/components/schemas/Result'
        meta:
          $ref: '#/components/schemas/Meta'
      additionalProperties: {}
    Result:
      type: object
      required:
        - affectedPkgs
        - issuesData
        - remediation
      properties:
        affectedPkgs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AffectedPackage'
        issuesData:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IssueData'
        remediation:
          $ref: '#/components/schemas/Remediation'
      additionalProperties: {}
    Severity:
      type: string
      enum:
        - none
        - low
        - medium
        - high
        - critical
    UpgradePackage:
      type: object
      properties:
        upgradeTo:
          type: string
        upgrades:
          type: array
          items:
            type: string
        vulns:
          type: array
          items:
            type: string
        isTransitive:
          type: boolean
      additionalProperties: {}
    UpgradePath:
      type: object
      required:
        - path
      properties:
        path:
          type: array
          items:
            $ref: '#/components/schemas/PackageUpgrade'
      additionalProperties: {}
    rfc3339Microseconds:
      type: string
      example: 2024-03-11T09:53:59.174248Z
      description: An RFC3339 timestamp with up to microsecond resolution.
servers:
  - url: /v1
    description: v1 API server
    variables: {}
