// Package clients provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package clients

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InteractionStage.
const (
	Cicd     InteractionStage = "cicd"
	Dev      InteractionStage = "dev"
	Prchecks InteractionStage = "prchecks"
	Unknown  InteractionStage = "unknown"
)

// ActualVersion Resolved API version
type ActualVersion = string

// AnalyticsAttributes defines model for AnalyticsAttributes.
type AnalyticsAttributes struct {
	Interaction Interaction `json:"interaction"`
	Runtime     *Runtime    `json:"runtime,omitempty"`
}

// AnalyticsData defines model for AnalyticsData.
type AnalyticsData struct {
	Attributes AnalyticsAttributes `json:"attributes"`

	// Type The type of data ("analytics").
	Type string `json:"type"`
}

// AnalyticsRequestBody defines model for AnalyticsRequestBody.
type AnalyticsRequestBody struct {
	Data AnalyticsData `json:"data"`
}

// Application The application name, e.g. snyk-ls. The version of the integration.
type Application struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Environment The environment for the integration (e.g., IntelliJ Ultimate, Pycharm). The version of the integration environment (e.g. 2023.3)
type Environment struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	// Code An application-specific error code, expressed as a string value.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Id A unique identifier for this particular occurrence of the problem.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Links A link that leads to further details about this particular occurrance of the problem.
	Links  *ErrorLink              `json:"links,omitempty"`
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Source *struct {
		// Parameter A string indicating which URI query parameter caused the error.
		Parameter *string `json:"parameter,omitempty"`

		// Pointer A JSON Pointer [RFC6901] to the associated entity in the request document.
		Pointer *string `json:"pointer,omitempty"`
	} `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status"`

	// Title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title *string `json:"title,omitempty"`
}

// ErrorDocument defines model for ErrorDocument.
type ErrorDocument struct {
	Errors  []Error `json:"errors"`
	Jsonapi JsonApi `json:"jsonapi"`
}

// ErrorLink A link that leads to further details about this particular occurrance of the problem.
type ErrorLink struct {
	About *LinkProperty `json:"about,omitempty"`
}

// Integration TODO UPDATE with correct samples of integration name. The name of the integration, could be a plugin or extension (e.g. Snyk Security plugin for intelliJ). The version of the integration (2.3.4).
type Integration struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Interaction defines model for Interaction.
type Interaction struct {
	// Categories The category vector used to describe the interaction in detail, "oss","test".
	Categories *[]string           `json:"categories,omitempty"`
	Errors     *[]InteractionError `json:"errors,omitempty"`

	// Extension Optional additional extension.
	//
	// Only strings, integers, and boolean values are allowed.
	Extension *map[string]interface{} `json:"extension,omitempty"`

	// Id The client-generated ID of the interaction event in the form of  `urn:snyk:interaction:00000000-0000-0000-0000-000000000000`
	Id string `json:"id"`

	// Results The result of the interaction. Could be a something like this [{"name": "critical", "count": 0}].
	// Only strings, integers, and boolean values are allowed.
	Results *[]map[string]interface{} `json:"results,omitempty"`

	// Stage The stage of the SDLC where the Interaction occurred, such as"dev"|"cicd"|"prchecks"|"unknown".
	Stage *InteractionStage `json:"stage,omitempty"`

	// Status Status would be "success" or "failure", where success means the action was executed,  while failure means it didn't run.
	Status string `json:"status"`
	Target Target `json:"target"`

	// TimestampMs The timestamp in epoch milliseconds when the interaction was started in UTC (Zulu time).
	TimestampMs int64 `json:"timestamp_ms"`

	// Type The type of interaction, could be "Scan done". Scan Done indicates that a test was run no  matter if the CLI or IDE ran it, other types can be freely chosen types.
	Type string `json:"type"`
}

// InteractionStage The stage of the SDLC where the Interaction occurred, such as"dev"|"cicd"|"prchecks"|"unknown".
type InteractionStage string

// InteractionError defines model for InteractionError.
type InteractionError struct {
	// Code The HTTP specific error code.
	Code *string `json:"code,omitempty"`

	// Id Error identifier corresponding to the errors defined in the error catalog.
	//
	// `https://docs.snyk.io/scan-with-snyk/error-catalog`
	Id string `json:"id"`
}

// JsonApi defines model for JsonApi.
type JsonApi struct {
	// Version Version of the JSON API specification this server supports.
	Version string `json:"version"`
}

// LinkProperty defines model for LinkProperty.
type LinkProperty struct {
	union json.RawMessage
}

// LinkProperty0 A string containing the link’s URL.
type LinkProperty0 = string

// LinkProperty1 defines model for .
type LinkProperty1 struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`

	// Meta Free-form object that may contain non-standard information.
	Meta *Meta `json:"meta,omitempty"`
}

// Meta Free-form object that may contain non-standard information.
type Meta map[string]interface{}

// Performance The scan duration in milliseconds
type Performance struct {
	DurationMs int64 `json:"duration_ms"`
}

// Platform The operating system and the architecture (AMD64, ARM64, 386, ALPINE).
type Platform struct {
	Arch string `json:"arch"`
	Os   string `json:"os"`
}

// QueryVersion Requested API version
type QueryVersion = string

// Runtime defines model for Runtime.
type Runtime struct {
	// Application The application name, e.g. snyk-ls. The version of the integration.
	Application *Application `json:"application,omitempty"`

	// Environment The environment for the integration (e.g., IntelliJ Ultimate, Pycharm). The version of the integration environment (e.g. 2023.3)
	Environment *Environment `json:"environment,omitempty"`

	// Integration TODO UPDATE with correct samples of integration name. The name of the integration, could be a plugin or extension (e.g. Snyk Security plugin for intelliJ). The version of the integration (2.3.4).
	Integration *Integration `json:"integration,omitempty"`

	// Performance The scan duration in milliseconds
	Performance *Performance `json:"performance,omitempty"`

	// Platform The operating system and the architecture (AMD64, ARM64, 386, ALPINE).
	Platform *Platform `json:"platform,omitempty"`
}

// Target defines model for Target.
type Target struct {
	// Id A purl is a URL composed of seven components.
	// scheme:type/namespace/name@version?qualifiers#subpath
	//
	// The purl specification is available here:
	//
	// `https://github.com/package-url/purl-spec`
	//
	// Some purl examples
	//
	// `pkg:github/package-url/purl-spec@244fd47e07d1004f0aed9c`
	//
	// `pkg:npm/%40angular/animation@12.3.1`
	//
	// `pkg:pypi/django@1.11.1`
	Id string `json:"id"`
}

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID

// N400 defines model for 400.
type N400 = ErrorDocument

// N404 defines model for 404.
type N404 = ErrorDocument

// N500 defines model for 500.
type N500 = ErrorDocument

// CreateAnalyticsParams defines parameters for CreateAnalytics.
type CreateAnalyticsParams struct {
	// Version The requested version of the endpoint to process the request
	Version QueryVersion `form:"version" json:"version"`
}

// CreateAnalyticsJSONRequestBody defines body for CreateAnalytics for application/json ContentType.
type CreateAnalyticsJSONRequestBody = AnalyticsRequestBody

// AsLinkProperty0 returns the union data inside the LinkProperty as a LinkProperty0
func (t LinkProperty) AsLinkProperty0() (LinkProperty0, error) {
	var body LinkProperty0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty0 overwrites any union data inside the LinkProperty as the provided LinkProperty0
func (t *LinkProperty) FromLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty0 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty0
func (t *LinkProperty) MergeLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsLinkProperty1 returns the union data inside the LinkProperty as a LinkProperty1
func (t LinkProperty) AsLinkProperty1() (LinkProperty1, error) {
	var body LinkProperty1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty1 overwrites any union data inside the LinkProperty as the provided LinkProperty1
func (t *LinkProperty) FromLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty1 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty1
func (t *LinkProperty) MergeLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t LinkProperty) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LinkProperty) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateAnalyticsWithBody request with any body
	CreateAnalyticsWithBody(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAnalytics(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, body CreateAnalyticsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateAnalyticsWithBody(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAnalyticsRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAnalytics(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, body CreateAnalyticsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAnalyticsRequest(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateAnalyticsRequest calls the generic CreateAnalytics builder with application/json body
func NewCreateAnalyticsRequest(server string, orgId OrgId, params *CreateAnalyticsParams, body CreateAnalyticsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAnalyticsRequestWithBody(server, orgId, params, "application/json", bodyReader)
}

// NewCreateAnalyticsRequestWithBody generates requests for CreateAnalytics with any type of body
func NewCreateAnalyticsRequestWithBody(server string, orgId OrgId, params *CreateAnalyticsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/analytics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateAnalyticsWithBodyWithResponse request with any body
	CreateAnalyticsWithBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAnalyticsResponse, error)

	CreateAnalyticsWithResponse(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, body CreateAnalyticsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAnalyticsResponse, error)
}

type CreateAnalyticsResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	JSON201                  *map[string]interface{}
	ApplicationvndApiJSON400 *N400
	ApplicationvndApiJSON404 *N404
	ApplicationvndApiJSON500 *N500
}

// Status returns HTTPResponse.Status
func (r CreateAnalyticsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAnalyticsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateAnalyticsWithBodyWithResponse request with arbitrary body returning *CreateAnalyticsResponse
func (c *ClientWithResponses) CreateAnalyticsWithBodyWithResponse(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAnalyticsResponse, error) {
	rsp, err := c.CreateAnalyticsWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAnalyticsResponse(rsp)
}

func (c *ClientWithResponses) CreateAnalyticsWithResponse(ctx context.Context, orgId OrgId, params *CreateAnalyticsParams, body CreateAnalyticsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAnalyticsResponse, error) {
	rsp, err := c.CreateAnalytics(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAnalyticsResponse(rsp)
}

// ParseCreateAnalyticsResponse parses an HTTP response from a CreateAnalyticsWithResponse call
func ParseCreateAnalyticsResponse(rsp *http.Response) (*CreateAnalyticsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAnalyticsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}
